# Conversion
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: rouge

destination: C:/apache-tomcat-7.0.59/webapps/ROOT
baseurl: ""